const DEFAULT_SETTINGS = {
  enabled: true,
  debugMode: false,
  visibleTiers: ["tier1", "tier2", "tier3", "tier4", "tier5", "tier6"],
  currentTierPage: "tier1",
  skillPoints: 0,
  unlockedSkills: [],
  skillLevels: {},
  lastLevel: 1,
  totalEarnedSP: 0,
  totalSpentSP: 0,
  currentMana: 100,
  maxMana: 100,
  activeSkillStates: {},
  combatSkillStates: {},
  manaRegenRate: 1,
  lastManaRegen: 0,
};

const INNATE_PASSIVES = [
  {
    id: "detoxification",
    name: "Detoxification",
    mode: "auto-scaling",
    desc: "An innate System passive that automatically purges toxins, shortens harmful statuses, and grows stronger with your level and rank.",
    lore: "The System continuously cleanses Jin-Woo's body so poison and abnormal conditions fail to linger for long.",
    statusText: "Always Active • Auto-Scaling",
  },
  {
    id: "tenacity",
    name: "Tenacity",
    mode: "conditional",
    desc: "An innate survival instinct that triggers automatically when your HP falls into the danger zone.",
    lore: "When Jin-Woo is pushed toward death, the System hardens him and halves the force of incoming damage.",
    statusText: "Always Active • Triggers below 30% HP",
  },
];

const HIDDEN_BLESSINGS = [
  {
    id: "blessing_of_kandiaru",
    name: "Blessing of Kandiaru",
    mode: "rank-scaling",
    desc: "A hidden blessing that subtly accelerates experience gain and natural growth as your rank rises.",
    lore: "A secret favor woven into the System by Kandiaru himself, sharpening Jin-Woo's growth from the very start.",
    statusText: "Always Active • Rank-Scaled",
  },
];

const SKILL_TREE = {
  tier1: {
    name: "System Foundation",
    tier: 1,
    maxLevel: 10,
    baseCost: 1,
    upgradeCostMultiplier: 1.5,
    growthRate: 1.0,
    skills: [
      {
        id: "longevity",
        name: "Longevity",
        desc: "Stabilize your life force and accelerate both HP and mana recovery for prolonged battles.",
        lore: "A long-endurance System passive adapted here to keep Jin-Woo battle-ready between heavy exchanges.",
        requirement: { level: 15, vitality: 10, intelligence: 8 },
        baseEffect: { hpRegenBonus: 0.12, manaRegenBonus: 0.12 },
        perLevelEffect: { hpRegenBonus: 0.05, manaRegenBonus: 0.05 },
      },
    ],
  },
  tier2: {
    name: "Assassin Job",
    tier: 2,
    maxLevel: 15,
    baseCost: 3,
    upgradeCostMultiplier: 2.0,
    growthRate: 1.5,
    skills: [
      {
        id: "sprint",
        name: "Sprint",
        desc: "Explosive footwork that lowers the cooldown of your basic attacks and offensive combat skills.",
        lore: "Jin-Woo's assassin footwork turns movement into tempo, letting each attack come faster than enemies expect.",
        requirement: { level: 35, agility: 10 },
        baseEffect: { attackCooldownReduction: 0.04 },
        perLevelEffect: { attackCooldownReduction: 0.01 },
      },
      {
        id: "mutilation",
        name: "Mutilation",
        desc: "Sharpen execution strikes so every critical hit tears deeper into the target.",
        lore: "A murderous finishing technique that tears through weakened targets.",
        requirement: { level: 45, strength: 10, skills: ["advanced_dagger_techniques"] },
        baseEffect: { critDamageBonus: 0.1 },
        perLevelEffect: { critDamageBonus: 0.035 },
      },
      {
        id: "vital_points_targeting",
        name: "Vital Points Targeting",
        desc: "Read enemy weak points and strike decisively. Increases crit chance.",
        lore: "Assassin perception that turns openings into instant kill lines.",
        requirement: { level: 55, perception: 15 },
        baseEffect: { critBonus: 0.012 },
        perLevelEffect: { critBonus: 0.007 },
      },
      {
        id: "advanced_dagger_techniques",
        name: "Dagger Arts",
        desc: "Refined dagger combat patterns that raise critical precision.",
        lore: "Advanced dagger techniques honed through assassin-class combat.",
        requirement: { level: 30, strength: 5 },
        baseEffect: { critBonus: 0.008 },
        perLevelEffect: { critBonus: 0.005 },
      },
      {
        id: "dagger_throw",
        name: "Dagger Throw",
        desc: "Refine ranged dagger pressure so thrown strikes hit harder and punish distant openings.",
        lore: "A ranged dagger barrage that keeps pressure without sacrificing lethality.",
        requirement: { level: 65, agility: 15 },
        baseEffect: { daggerThrowDamageBonus: 0.12 },
        perLevelEffect: { daggerThrowDamageBonus: 0.03 },
      },
      {
        id: "stealth",
        name: "Stealth",
        desc: "Suppress your presence and move through shadows unnoticed. Increases XP and crit chance.",
        lore: "Presence concealment that turns a hunter into a ghost.",
        requirement: { level: 75, agility: 20, skills: ["advanced_dagger_techniques"] },
        baseEffect: { xpBonus: 0.02, critBonus: 0.01 },
        perLevelEffect: { xpBonus: 0.015, critBonus: 0.008 },
      },
    ],
  },
  tier3: {
    name: "Job Change - Necromancer",
    tier: 3,
    maxLevel: 20,
    baseCost: 5,
    upgradeCostMultiplier: 2.5,
    growthRate: 2.0,
    skills: [
      {
        id: "shadow_preservation",
        name: "Shadow Preservation",
        desc: "Unlock shadow storage. Shadows you claim are preserved in the archive and can be stored, viewed, and redeployed.",
        lore: "A preserved shadow can be stored, redeployed, and observed through at will.",
        requirement: { level: 100, rank: "B" },
        unlockOnly: true,
        baseEffect: {},
        perLevelEffect: {},
      },
      {
        id: "shadow_extraction",
        name: "Shadow Extraction",
        desc: "Unlock the Arise command. Extract shadows from dungeon bosses, defeated enemies, and gain a chance to arise shadows when sending messages.",
        lore: "The command that turns death into reinforcements.",
        requirement: { level: 95, rank: "B" },
        unlockOnly: true,
        baseEffect: {},
        perLevelEffect: {},
      },
      {
        id: "shadow_army_expansion",
        name: "Shadow Army Expansion",
        desc: "Unlock shadow army stat scaling. Your army's size passively boosts your XP and stats.",
        lore: "The army grows from elite summons into a complete military force. Each shadow added sharpens the Monarch's edge.",
        requirement: { level: 180, skills: ["shadow_extraction", "shadow_preservation"] },
        unlockOnly: true,
        baseEffect: {},
        perLevelEffect: {},
      },
    ],
  },
  tier4: {
    name: "Monarch Awakening",
    tier: 4,
    maxLevel: 25,
    baseCost: 10,
    upgradeCostMultiplier: 3.0,
    growthRate: 3.0,
    skills: [
      {
        id: "shadow_senses",
        name: "Shadow Senses",
        unlockOnly: true,
        desc: "Perceive the battlefield through deployed shadows and distant scouts.",
        lore: "Jin-Woo can share vision and awareness through the shadows under his command.",
        requirement: { level: 250, skills: ["shadow_preservation"] },
        baseEffect: {},
        perLevelEffect: {},
      },
      {
        id: "shadow_exchange",
        name: "Shadow Exchange",
        maxLevel: 5,
        desc: "Unlock the Shadow Exchange plugin. Each level reduces the teleport cooldown.",
        lore: "Switch places with a shadow instantly to control range and tempo.",
        requirement: { level: 275, skills: ["shadow_army_expansion"] },
        baseEffect: {},
        perLevelEffect: {},
      },
      {
        id: "rulers_authority",
        name: "Ruler's Authority",
        maxLevel: 3,
        desc: "Telekinetic force inherited from the Rulers. Unlocks the Ruler's Authority plugin and dungeon combat skill.",
        lore: "The will-based force that crushes or controls without touch — a power distinct from the shadows.",
        requirement: { level: 300, rank: "A" },
        baseEffect: {},
        perLevelEffect: {},
      },
      {
        id: "domain_of_the_monarch",
        name: "Monarch's Domain",
        desc: "Exert the Shadow Monarch's territory. Unlocks the Domain Expansion dungeon combat skill that buffs all shadow stats.",
        lore: "Within this domain, the Shadow Monarch is absolute.",
        requirement: { level: 350, intelligence: 30, skills: ["rulers_authority", "shadow_senses"] },
        baseEffect: {},
        perLevelEffect: {},
      },
    ],
  },
  tier5: {
    name: "Ashborn Will",
    tier: 5,
    maxLevel: 30,
    baseCost: 15,
    upgradeCostMultiplier: 3.5,
    growthRate: 4.0,
    skills: [
      {
        id: "black_heart_awakened",
        name: "Black Heart",
        desc: "Absorb Ashborn's Black Heart — a permanent flood of 100,000 dark mana. Binary unlock, not upgradeable.",
        lore: "The crystallised core of the Shadow Monarch. Its mana is limitless, its gift irreversible.",
        requirement: {
          level: 1000,
          strength: 90,
          agility: 90,
          skills: ["shadow_exchange", "rulers_authority", "domain_of_the_monarch"],
        },
        unlockOnly: true,
        baseEffect: { flatMana: 100000 },
        perLevelEffect: {},
      },
      {
        id: "ashborns_will",
        name: "Ashborn's Will",
        desc: "Inherit the undying resolve of the original Shadow Monarch. Ashborn endured millennia of war against the Rulers — his indomitable will now strengthens every aspect of your power.",
        lore: "Ashborn chose you as successor not for strength, but for the will that refused to break.",
        requirement: { level: 1400, skills: ["black_heart_awakened"] },
        baseEffect: { xpBonus: 0.2, allStatBonus: 0.1, critBonus: 0.06, questBonus: 0.08 },
        perLevelEffect: {
          xpBonus: 0.06,
          allStatBonus: 0.026,
          critBonus: 0.016,
          questBonus: 0.022,
        },
      },
      {
        id: "dragons_fear",
        name: "Dragon's Fear",
        desc: "Unleash Kamish's draconic terror as a combat skill. No passive bonuses — pure combat ability unlock.",
        lore: "The fear that paralysed an entire nation's S-Rank hunters, now yours to command.",
        requirement: { level: 1600, skills: ["ashborns_will"] },
        unlockOnly: true,
        baseEffect: {},
        perLevelEffect: {},
      },
    ],
  },
  tier6: {
    name: "True Shadow Monarch",
    tier: 6,
    maxLevel: 35,
    baseCost: 25,
    upgradeCostMultiplier: 4.0,
    growthRate: 5.0,
    skills: [
      {
        id: "eternal_shadow_monarch",
        name: "True Shadow Monarch",
        desc: "The final ascension. +300% all stats, 100% arise chance, 90% damage reduction (always active), -75% mana costs, double HP/Mana recovery, and accelerated shadow growth.",
        lore: "No longer successor — you are the eternal Shadow Monarch. Every shadow bows, every stat surges, every enemy kneels.",
        requirement: { level: 2000, skills: ["black_heart_awakened", "ashborns_will", "dragons_fear"] },
        unlockOnly: true,
        baseEffect: {
          allStatBonus: 3.0,
          hpRegenBonus: 1.0,
          manaRegenBonus: 1.0,
          manaCostReduction: 0.75,
          tenacityThreshold: 1.0,
          tenacityDamageReduction: 0.9,
          ariseChanceOverride: 1.0,
          shadowGrowthMultiplier: 3.0,
        },
        perLevelEffect: {},
      },
    ],
  },
};

const ACTIVE_SKILL_DEFS = {
  stealth_technique: {
    id: "stealth_technique",
    name: "Stealth Technique",
    desc: "Disappear from hostile awareness. +20% crit chance and +15% XP while active.",
    lore: "Conceal your presence, close distance, and strike before you're seen.",
    manaCost: 200,
    durationMs: null,
    sustain: {
      manaPerTick: 10,
      tickMs: 1000,
      policy: "never_deplete",
      regenSafetyMultiplier: 0.9,
      minManaFloor: 1,
    },
    cooldownMs: 25 * 60 * 1000,
    effect: { xpMultiplier: 1.15, critChanceBonus: 0.20 },
    unlock: { passiveSkill: "stealth", passiveLevel: 3 },
  },
};

const ACTIVE_SKILL_ORDER = [
  "stealth_technique",
];

const DUNGEON_COMBAT_SKILL_DEFS = {
  mutilation: {
    id: "mutilation",
    name: "Mutilation",
    buttonLabel: "MUTILATE",
    desc: "Unleash a rapid-fire chain of critical dagger slashes that rip the target apart. Every hit is a critical strike. Evolved from Critical Attack — overwhelms regenerating enemies by severing faster than they heal.",
    lore: "The evolved form of Fatal Strike. Jinwoo's daggers move faster than sight — each cut a guaranteed critical, each slash aimed at a weak point. Even the Monarch of Destruction could not withstand this relentless onslaught.",
    manaCost: 70,
    cooldownMs: 90 * 1000,
    minimumCooldownMs: 35 * 1000,
    damageMultiplier: 2.6,
    forceCritical: true,
    executeThreshold: 0.35,
    executeMultiplier: 1.35,
    targeting: "single",
    unlock: { passiveSkill: "mutilation", passiveLevel: 5 },
  },
  dagger_throw: {
    id: "dagger_throw",
    name: "Dagger Throw",
    buttonLabel: "DAGGER THROW",
    desc: "Hurl shadow-laced daggers at enemies from range. Hits multiple mobs in a line or pressures a boss with rapid precision strikes controlled via Ruler's Authority.",
    lore: "Even at range, Jinwoo's dagger work retains its killing edge. Combined with telekinetic control, each thrown blade flies with guided precision — a ranged extension of the assassin's lethal craft.",
    manaCost: 35,
    cooldownMs: 30 * 1000,
    minimumCooldownMs: 10 * 1000,
    damageMultiplier: 1.35,
    passiveDamageBonusKey: "daggerThrowDamageBonus",
    targeting: "piercing",
    unlock: { passiveSkill: "dagger_throw", passiveLevel: 5 },
  },
  sprint_burst: {
    id: "sprint_burst",
    name: "Sprint",
    buttonLabel: "SPRINT",
    desc: "Channel assassin-class agility to boost all shadows' attack speed. The signature skill of the assassin job — costs almost nothing, turns brief windows into lethal opportunities.",
    lore: "The first active skill Jinwoo ever learned. At higher levels it evolves toward Quicksilver — a speed so absolute that enemies perceive only afterimages. In lore, costs merely 1 mana per minute to sustain.",
    manaCost: 15,
    cooldownMs: 300 * 1000,
    minimumCooldownMs: 120 * 1000,
    combatEffect: "speed_boost",
    speedBoost: {
      durationMs: 180000,
      durationPerLevel: 15000,
      attackCooldownReduction: 0.30,
      attackCooldownReductionPerLevel: 0.03,
    },
    unlock: { passiveSkill: "sprint", passiveLevel: 3 },
  },
  rulers_authority_force: {
    id: "rulers_authority_force",
    name: "Ruler's Authority",
    buttonLabel: "RULER'S FORCE",
    desc: "Project telekinetic force that crushes enemies in place — stuns the boss and immobilizes a portion of mobs while reducing their damage resistance. In lore, requires no mana — pure will-based power inherited from the Rulers.",
    lore: "The power of the Rulers, inherited through Ashborn. A will-based telekinetic force so overwhelming that even Monarch-level fighters cannot counter it unless they wield the same power. Jinwoo controls objects, daggers, and the very air around him — enemies are paralyzed under the weight of his intent.",
    manaCost: 0,
    cooldownMs: 120 * 1000,
    minimumCooldownMs: 45 * 1000,
    combatEffect: "debuff",
    debuff: {
      disableAttacksDurationMs: 5000,
      durationScaling: "double_per_level",
      damageResistReduction: 0.15,
      resistReductionPerLevel: 0.05,
      mobTargetPercent: 0.25,
      mobTargetPercentPerLevel: 0.05,
    },
    unlock: { passiveSkill: "rulers_authority", passiveLevel: 2 },
  },
  domain_expansion: {
    id: "domain_expansion",
    name: "Monarch's Domain",
    buttonLabel: "DOMAIN",
    desc: "Expand the Shadow Monarch's domain across the battlefield. All deployed shadow soldiers receive +50% to all stats. Within this space, the Monarch has absolute authority.",
    lore: "The Monarch's shadow spreads across the predetermined space, creating a territory where the Shadow Monarch's power is absolute. Every shadow soldier fights at full strength without restriction — their stats amplified by the Monarch's will. Even the terrain bends to Jinwoo's command within the domain.",
    manaCost: 100,
    cooldownMs: 180 * 1000,
    minimumCooldownMs: 60 * 1000,
    combatEffect: "shadow_buff",
    shadowBuff: {
      durationMs: 30000,
      durationPerLevel: 5000,
      allStatMultiplier: 1.50,
      allStatMultiplierPerLevel: 0.05,
    },
    unlock: { passiveSkill: "domain_of_the_monarch", passiveLevel: 3 },
  },
  bloodlust_aura: {
    id: "bloodlust_aura",
    name: "Bloodlust",
    buttonLabel: "BLOODLUST",
    desc: "Project murderous intent that induces intense fear — paralyzes all mobs and reduces the boss's stats by 50%. The fear effect lasts 1 minute. Affects multiple targets simultaneously.",
    lore: "An aura of pure killing intent so overwhelming that even S-Rank hunters cannot move. Bloodlust magically intimidates targets into submission, crushing their will and halving their strength. The fear-based effect wears off after one minute, but the psychological damage lingers.",
    manaCost: 100,
    cooldownMs: 120 * 1000,
    minimumCooldownMs: 40 * 1000,
    combatEffect: "bloodlust",
    bloodlust: {
      baseDurationMs: 60000,
      durationPerLevel: 10000,
      mobParalysisFull: true,
      bossStatReduction: 0.50,
      bossStatReductionPerLevel: 0.03,
      bossDurationMultiplier: 0.5,
    },
    unlock: { passiveSkill: "advanced_dagger_techniques", passiveLevel: 8 },
  },
  dragons_fear_roar: {
    id: "dragons_fear_roar",
    name: "Dragon's Fear",
    buttonLabel: "DRAGON'S FEAR",
    desc: "Release a mana-infused shout from the soul that drives anyone weaker into intense despair and panic. Paralyzes all mobs at or below your rank. Boss receives reduced duration based on rank difference. Indiscriminate — affects all weaker beings in range.",
    lore: "Obtained from Kamish's rune stone, this is the draconic wave of terror that once paralyzed an entire nation's S-Rank hunters. The shout is indiscriminate — it affects anyone weaker than the user in their vicinity. Jinwoo ironically used Kamish's own power against Antares and the Monarchs in the final war.",
    manaCost: 120,
    cooldownMs: 150 * 1000,
    minimumCooldownMs: 50 * 1000,
    combatEffect: "fear",
    fear: {
      baseDurationMs: 8000,
      durationPerLevel: 2000,
      bossResistPerRankAbove: 0.35,
      bossDurationMultiplier: 0.4,
      mobParalysisFull: true,
    },
    unlock: { passiveSkill: "dragons_fear", passiveLevel: 1 },
  },
};

const DUNGEON_COMBAT_SKILL_ORDER = ["mutilation", "dagger_throw", "sprint_burst", "bloodlust_aura", "rulers_authority_force", "domain_expansion", "dragons_fear_roar"];

function createSkillTreeData() {
  return {
    defaultSettings: structuredClone(DEFAULT_SETTINGS),
    innatePassives: structuredClone(INNATE_PASSIVES),
    hiddenBlessings: structuredClone(HIDDEN_BLESSINGS),
    skillTree: structuredClone(SKILL_TREE),
    activeSkillDefs: structuredClone(ACTIVE_SKILL_DEFS),
    activeSkillOrder: [...ACTIVE_SKILL_ORDER],
    dungeonCombatSkillDefs: structuredClone(DUNGEON_COMBAT_SKILL_DEFS),
    dungeonCombatSkillOrder: [...DUNGEON_COMBAT_SKILL_ORDER],
  };
}

module.exports = { createSkillTreeData };
