const DEFAULT_SETTINGS = {
  enabled: true,
  debugMode: false,
  visibleTiers: ["tier1", "tier2", "tier3", "tier4", "tier5", "tier6"],
  currentTierPage: "tier1",
  skillPoints: 0,
  unlockedSkills: [],
  skillLevels: {},
  lastLevel: 1,
  totalEarnedSP: 0,
  totalSpentSP: 0,
  currentMana: 100,
  maxMana: 100,
  activeSkillStates: {},
  manaRegenRate: 1,
  lastManaRegen: 0,
};

const SKILL_TREE = {
  tier1: {
    name: "Basic Abilities",
    tier: 1,
    maxLevel: 10,
    baseCost: 1,
    upgradeCostMultiplier: 1.5,
    growthRate: 1.0,
    skills: [
      {
        id: "shadow_extraction",
        name: "Shadow Extraction Mastery",
        desc: "Mastery over extracting shadows from defeated enemies. Each level increases XP gain.",
        lore: "The passive ability to extract shadows and turn them into your army.",
        requirement: { level: 5 },
        baseEffect: { xpBonus: 0.02 },
        perLevelEffect: { xpBonus: 0.02 },
      },
      {
        id: "shadow_preservation",
        name: "Shadow Preservation",
        desc: "Preserve and monitor shadows through their senses. Increases long message XP.",
        lore: "Store your shadow army and perceive the world through their eyes.",
        requirement: { level: 8 },
        baseEffect: { longMsgBonus: 0.03 },
        perLevelEffect: { longMsgBonus: 0.03 },
      },
      {
        id: "daggers_dance",
        name: "Dagger's Dance",
        desc: "Jin-Woo's signature dual-dagger combat style. Increases crit chance.",
        lore: "The dance of blades that cut through even S-Rank hunters.",
        requirement: { level: 10, strength: 5 },
        baseEffect: { critBonus: 0.01 },
        perLevelEffect: { critBonus: 0.01 },
      },
      {
        id: "kandiarus_blessing",
        name: "Kandiaru's Blessing",
        desc: "The System Architect's gift. Passively increases XP from all sources.",
        lore: "A hidden blessing woven into the System itself by its creator.",
        requirement: { level: 15, intelligence: 5 },
        baseEffect: { xpBonus: 0.015 },
        perLevelEffect: { xpBonus: 0.015 },
      },
    ],
  },
  tier2: {
    name: "Intermediate Abilities",
    tier: 2,
    maxLevel: 15,
    baseCost: 3,
    upgradeCostMultiplier: 2.0,
    growthRate: 1.5,
    skills: [
      {
        id: "shadow_exchange",
        name: "Shadow Exchange Efficiency",
        desc: "Efficient conversion of shadows into power. Significantly increases XP gain.",
        lore: "Passively trade shadows for power boosts.",
        requirement: { level: 50, skills: ["shadow_extraction"] },
        baseEffect: { xpBonus: 0.05 },
        perLevelEffect: { xpBonus: 0.05 },
      },
      {
        id: "arise",
        name: "Shadow Command Mastery",
        desc: "Mastery over commanding your shadow army. Increases all stat bonuses.",
        lore: "Passive command over shadows that brings them to life.",
        requirement: { level: 60, skills: ["shadow_preservation"] },
        baseEffect: { allStatBonus: 0.02 },
        perLevelEffect: { allStatBonus: 0.02 },
      },
      {
        id: "gate_creation",
        name: "Gate Creation",
        desc: "Open black-and-purple gates to other worlds. Increases quest rewards.",
        lore: "Tear open dimensional gates at will, each one a path to greater power.",
        requirement: { level: 75, intelligence: 15 },
        baseEffect: { questBonus: 0.04 },
        perLevelEffect: { questBonus: 0.04 },
      },
      {
        id: "dagger_rush",
        name: "Dagger Rush",
        desc: "Barrage opponents with daggers from all directions. Increases crit chance significantly.",
        lore: "A relentless storm of blades that leaves no opening for escape.",
        requirement: { level: 80, agility: 15 },
        baseEffect: { critBonus: 0.02 },
        perLevelEffect: { critBonus: 0.02 },
      },
      {
        id: "stealth",
        name: "Shadow Stealth",
        desc: "Passive ability to move unseen through shadows. Increases XP and crit chance.",
        lore: "Become one with the shadows.",
        requirement: { level: 90, agility: 20 },
        baseEffect: { xpBonus: 0.03, critBonus: 0.015 },
        perLevelEffect: { xpBonus: 0.03, critBonus: 0.015 },
      },
    ],
  },
  tier3: {
    name: "Advanced Abilities",
    tier: 3,
    maxLevel: 20,
    baseCost: 5,
    upgradeCostMultiplier: 2.5,
    growthRate: 2.0,
    skills: [
      {
        id: "monarchs_domain",
        name: "Monarch's Domain",
        desc: "Exert the Monarch's territory. Massive XP and stat bonuses.",
        lore: "Within this domain, the Shadow Monarch is absolute.",
        requirement: { level: 150, intelligence: 30, skills: ["gate_creation"] },
        baseEffect: { xpBonus: 0.08, allStatBonus: 0.03 },
        perLevelEffect: { xpBonus: 0.08, allStatBonus: 0.03 },
      },
      {
        id: "ruler_authority",
        name: "Ruler's Presence",
        desc: "Passive aura of absolute authority. Increases all bonuses.",
        lore: "The passive power to rule over all.",
        requirement: { level: 200, skills: ["arise"] },
        baseEffect: { xpBonus: 0.06, allStatBonus: 0.04, critBonus: 0.02 },
        perLevelEffect: { xpBonus: 0.06, allStatBonus: 0.04, critBonus: 0.02 },
      },
      {
        id: "shadow_army",
        name: "Shadow Legion Mastery",
        desc: "Mastery over commanding a legion of shadows. Massive XP and quest bonuses.",
        lore: "Passively build an army of shadows to fight for you.",
        requirement: { level: 250, skills: ["shadow_exchange", "arise"] },
        baseEffect: { xpBonus: 0.1, questBonus: 0.06 },
        perLevelEffect: { xpBonus: 0.1, questBonus: 0.06 },
      },
      {
        id: "monarch_power",
        name: "Monarch's Aura",
        desc: "Passive aura of monarch-level power. Extreme bonuses.",
        lore: "The power of a Monarch passively flows through you.",
        requirement: { level: 300, strength: 50, agility: 50 },
        baseEffect: { xpBonus: 0.12, critBonus: 0.03, allStatBonus: 0.05 },
        perLevelEffect: { xpBonus: 0.12, critBonus: 0.03, allStatBonus: 0.05 },
      },
    ],
  },
  tier4: {
    name: "Master Abilities",
    tier: 4,
    maxLevel: 25,
    baseCost: 10,
    upgradeCostMultiplier: 3.0,
    growthRate: 3.0,
    skills: [
      {
        id: "shadow_monarch",
        name: "Shadow Monarch's Presence",
        desc: "Passive presence of the Shadow Monarch. Ultimate power over shadows.",
        lore: "The ultimate form - passive ruler of all shadows.",
        requirement: { level: 500, skills: ["monarch_power", "shadow_army"] },
        baseEffect: { xpBonus: 0.15, allStatBonus: 0.08, critBonus: 0.04 },
        perLevelEffect: { xpBonus: 0.15, allStatBonus: 0.08, critBonus: 0.04 },
      },
      {
        id: "ashborn_legacy",
        name: "Ashborn's Legacy",
        desc: "Passive inheritance of the first Shadow Monarch's power. Transcendent bonuses.",
        lore: "The legacy of Ashborn passively flows through you.",
        requirement: { level: 750, skills: ["shadow_monarch"] },
        baseEffect: { xpBonus: 0.2, allStatBonus: 0.1, critBonus: 0.05, questBonus: 0.08 },
        perLevelEffect: { xpBonus: 0.2, allStatBonus: 0.1, critBonus: 0.05, questBonus: 0.08 },
      },
    ],
  },
  tier5: {
    name: "Transcendent Abilities",
    tier: 5,
    maxLevel: 30,
    baseCost: 15,
    upgradeCostMultiplier: 3.5,
    growthRate: 4.0,
    skills: [
      {
        id: "rulers_domain",
        name: "Ruler's Domain",
        desc: "The opposing cosmic force. Absolute authority over existence.",
        lore: "Channel the Rulers' power - the cosmic opposite of the Monarchs.",
        requirement: { level: 1000, skills: ["ashborn_legacy"] },
        baseEffect: {
          xpBonus: 0.25,
          allStatBonus: 0.12,
          critBonus: 0.06,
          questBonus: 0.1,
          longMsgBonus: 0.15,
        },
        perLevelEffect: {
          xpBonus: 0.25,
          allStatBonus: 0.12,
          critBonus: 0.06,
          questBonus: 0.1,
          longMsgBonus: 0.15,
        },
      },
      {
        id: "shadow_realm",
        name: "Shadow Realm",
        desc: "Access the space between worlds. Transcendent XP and stat bonuses.",
        lore: "The dimension where shadows gather between life and death.",
        requirement: { level: 1200, skills: ["rulers_domain"] },
        baseEffect: { xpBonus: 0.3, allStatBonus: 0.15, critBonus: 0.08 },
        perLevelEffect: { xpBonus: 0.3, allStatBonus: 0.15, critBonus: 0.08 },
      },
      {
        id: "gate_ruler",
        name: "Gate Ruler",
        desc: "Command the Gates between dimensions. Massive bonuses.",
        lore: "Every Gate bends to your will, every dungeon opens at your command.",
        requirement: { level: 1400, skills: ["shadow_realm"] },
        baseEffect: { xpBonus: 0.35, allStatBonus: 0.18, critBonus: 0.1, questBonus: 0.12 },
        perLevelEffect: { xpBonus: 0.35, allStatBonus: 0.18, critBonus: 0.1, questBonus: 0.12 },
      },
    ],
  },
  tier6: {
    name: "Ultimate Abilities",
    tier: 6,
    maxLevel: 35,
    baseCost: 25,
    upgradeCostMultiplier: 4.0,
    growthRate: 5.0,
    skills: [
      {
        id: "dragons_fear",
        name: "Dragon's Fear",
        desc: "Overwhelming killing intent that paralyzes all. Ultimate bonuses.",
        lore: "An aura of terror that made even the Monarchs' armies hesitate.",
        requirement: { level: 1500, skills: ["gate_ruler"] },
        baseEffect: {
          xpBonus: 0.4,
          allStatBonus: 0.2,
          critBonus: 0.12,
          questBonus: 0.15,
          longMsgBonus: 0.2,
        },
        perLevelEffect: {
          xpBonus: 0.4,
          allStatBonus: 0.2,
          critBonus: 0.12,
          questBonus: 0.15,
          longMsgBonus: 0.2,
        },
      },
      {
        id: "ashborns_will",
        name: "Ashborn's Will",
        desc: "The first Shadow Monarch's undying resolve. Transcendent bonuses.",
        lore: "Ashborn's will persists across millennia, now flowing through you.",
        requirement: { level: 1750, skills: ["dragons_fear"] },
        baseEffect: { xpBonus: 0.45, allStatBonus: 0.25, critBonus: 0.15, questBonus: 0.18 },
        perLevelEffect: {
          xpBonus: 0.45,
          allStatBonus: 0.25,
          critBonus: 0.15,
          questBonus: 0.18,
        },
      },
      {
        id: "shadow_sovereign",
        name: "Shadow Sovereign",
        desc: "The Sovereign of Shadows - Ashborn's true title. Maximum possible power.",
        lore: "You have become the Shadow Sovereign, ruler of death and darkness.",
        requirement: { level: 2000, skills: ["ashborns_will"] },
        baseEffect: {
          xpBonus: 0.5,
          allStatBonus: 0.3,
          critBonus: 0.18,
          questBonus: 0.2,
          longMsgBonus: 0.25,
        },
        perLevelEffect: {
          xpBonus: 0.5,
          allStatBonus: 0.3,
          critBonus: 0.18,
          questBonus: 0.2,
          longMsgBonus: 0.25,
        },
      },
    ],
  },
};

const ACTIVE_SKILL_DEFS = {
  sprint: {
    id: "sprint",
    name: "Sprint",
    desc: "Channel Jinwoo's supernatural speed. +100% XP for a short burst.",
    lore: "A burst of speed that leaves afterimages in your wake.",
    manaCost: 30,
    durationMs: 5 * 60 * 1000,
    cooldownMs: 20 * 60 * 1000,
    effect: { xpMultiplier: 2.0 },
    unlock: { passiveSkill: "stealth", passiveLevel: 5 },
  },
  bloodlust: {
    id: "bloodlust",
    name: "Bloodlust",
    desc: "Unleash killing intent. +50% crit chance (uncapped during buff).",
    lore: "An aura of murderous intent that makes even S-Rank hunters freeze.",
    manaCost: 50,
    durationMs: 8 * 60 * 1000,
    cooldownMs: 30 * 60 * 1000,
    effect: { critChanceBonus: 0.50 },
    unlock: { passiveSkill: "daggers_dance", passiveLevel: 8 },
  },
  mutilate: {
    id: "mutilate",
    name: "Mutilate",
    desc: "Critical strike mastery. Next 10 messages are guaranteed crits.",
    lore: "A flurry of precise strikes, each one finding its mark.",
    manaCost: 40,
    durationMs: null,
    charges: 10,
    cooldownMs: 25 * 60 * 1000,
    effect: { guaranteedCrit: true },
    unlock: { passiveSkill: "dagger_rush", passiveLevel: 10 },
  },
  rulers_authority: {
    id: "rulers_authority",
    name: "Ruler's Authority",
    desc: "Telekinetic force amplifies all stats. +75% all stat bonuses.",
    lore: "The power to move objects with will alone, now amplifying your very being.",
    manaCost: 60,
    durationMs: 10 * 60 * 1000,
    cooldownMs: 45 * 60 * 1000,
    effect: { allStatMultiplier: 1.75 },
    unlock: { passiveSkill: "ruler_authority", passiveLevel: 10 },
  },
  shadow_exchange_active: {
    id: "shadow_exchange_active",
    name: "Shadow Exchange",
    desc: "Swap places with a shadow soldier. Double quest rewards for next quest.",
    lore: "Instantly switch positions with any shadow in your army.",
    manaCost: 25,
    durationMs: null,
    charges: 1,
    cooldownMs: 60 * 60 * 1000,
    effect: { questRewardMultiplier: 2.0 },
    unlock: { passiveSkill: "shadow_exchange", passiveLevel: 10 },
  },
  arise_active: {
    id: "arise_active",
    name: "Arise",
    desc: "Command shadows to rise. +200% Shadow Army buff power.",
    lore: "ARISE! The command that raises the dead to serve the Shadow Monarch.",
    manaCost: 80,
    durationMs: 15 * 60 * 1000,
    cooldownMs: 60 * 60 * 1000,
    effect: { shadowBuffMultiplier: 3.0 },
    unlock: { passiveSkill: "arise", passiveLevel: 12 },
  },
  monarchs_domain_active: {
    id: "monarchs_domain_active",
    name: "Monarch's Domain",
    desc: "Expand your domain of power. All bonuses +30% for the duration.",
    lore: "Within this domain, the Shadow Monarch reigns supreme over all.",
    manaCost: 100,
    durationMs: 20 * 60 * 1000,
    cooldownMs: 90 * 60 * 1000,
    effect: { globalMultiplier: 1.30 },
    unlock: { passiveSkill: "monarchs_domain", passiveLevel: 15 },
  },
};

const ACTIVE_SKILL_ORDER = [
  "sprint",
  "bloodlust",
  "mutilate",
  "rulers_authority",
  "shadow_exchange_active",
  "arise_active",
  "monarchs_domain_active",
];

function createSkillTreeData() {
  return {
    defaultSettings: structuredClone(DEFAULT_SETTINGS),
    skillTree: structuredClone(SKILL_TREE),
    activeSkillDefs: structuredClone(ACTIVE_SKILL_DEFS),
    activeSkillOrder: [...ACTIVE_SKILL_ORDER],
  };
}

module.exports = { createSkillTreeData };
