#!/usr/bin/env python3
"""
Convert font files to base64 data URIs for embedding in BetterDiscord plugin.
This is necessary because BetterDiscord's sandboxed environment blocks local file access.
"""

import base64
import os


def convert_font_to_base64(font_path):
    """Convert a font file to a base64 data URI."""
    with open(font_path, "rb") as f:
        font_data = f.read()
        base64_data = base64.b64encode(font_data).decode("utf-8")
        return base64_data


def get_mime_type(ext):
    """Get MIME type for font extension."""
    mime_types = {
        "woff2": "font/woff2",
        "woff": "font/woff",
        "ttf": "font/ttf",
        "otf": "font/otf",
    }
    return mime_types.get(ext.lower(), "application/octet-stream")


def main():
    fonts_dir = os.path.dirname(os.path.abspath(__file__))

    fonts = {
        "FriendorFoeBB": ["woff2", "woff", "ttf"],
        "SpeedySpaceGoatOddity": ["woff2", "woff", "ttf"],
    }

    print("// Auto-generated font data URIs for BetterDiscord plugin")
    print("// Generated by embed_fonts.py")
    print("// DO NOT EDIT MANUALLY")
    print()

    for font_name, formats in fonts.items():
        print(f"// {font_name} font data")
        font_data = {}

        for fmt in formats:
            font_path = os.path.join(fonts_dir, f"{font_name}.{fmt}")
            if os.path.exists(font_path):
                base64_data = convert_font_to_base64(font_path)
                mime_type = get_mime_type(fmt)
                font_data[fmt] = {
                    "base64": base64_data,
                    "mime": mime_type,
                    "format": (
                        "woff2"
                        if fmt == "woff2"
                        else "woff" if fmt == "woff" else "truetype"
                    ),
                }
                file_size = os.path.getsize(font_path)
                print(
                    f"// {fmt.upper()}: {file_size:,} bytes -> {len(base64_data):,} base64 chars"
                )
            else:
                print(f"// WARNING: {font_path} not found")

        if font_data:
            print(f"const {font_name.upper()}_FONT_DATA = {{")
            for fmt, data in font_data.items():
                print(f"  {fmt}: {{")
                print(f"    mime: '{data['mime']}',")
                print(f"    format: '{data['format']}',")
                print(f"    base64: '{data['base64']}'")
                print("  },")
            print("};")
            print()

    print("// Usage in plugin:")
    print(
        "// const fontSrc = `url('data:${FONT_DATA.woff2.mime};base64,${FONT_DATA.woff2.base64}') format('${FONT_DATA.woff2.format}'),"
    )
    print(
        "//                url('data:${FONT_DATA.woff.mime};base64,${FONT_DATA.woff.base64}') format('${FONT_DATA.woff.format}');"
    )


if __name__ == "__main__":
    main()
